### ISSUE TITLE
BeerPay 404

### ISSUE THREAD

**Issue by JesusTheHun** [OAuth2-Framework/server-bundle#51]
Hi !

I'm stunned by the work you did here !! I am really really interested in seeing this bundle released in a stable version, with a basic documentation. I saw you haven't commit for a while and thought a beer could bring you back online :D Unfortunately, your beerpay link is broken :/
Also, I've seen you are french, I am french too, I live in Paris, if you do too, maybe I can offer it to you in person !

**Comment by Spomky** [comment]
Hi,

No commit have been pushed for a while because at the moment [I am working on the library](https://github.com/OAuth2-Framework/server-library/commits/CQRS). As long as the library is not stable, this bundle can not be stable either.

The link to the beerpay page is now https://beerpay.io/OAuth2-Framework (I will update the link for all repositories). I will be happy to drink a beer with you, but I live near Grenoble. If I have the opportunity to go to Paris, then I will notify you.
